apiVersion: v1
kind: Service
metadata:
  name: tracking-number-generator
spec:
  selector:
    app: tracking-number-generator
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
