apiVersion: v1
kind: Service
metadata:
  name: tracking-number-generator
spec:
  selector:
    app: tracking-number-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
